# Site Settings
title: Beltram Maldant
url: 'https://beltram.github.io/resume/'
baseurl: '/resume'

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles-6

#Profile information
name: Beltram Maldant
tagline: Architect
age: 30
pic: profile.jpg
summary: "I am a software architect at Sopra Banking Software. I belong to a platform team in charge of delivering
tools and libraries to our 300+ developers. On a daily basis, I switch between architectural studies, implementations,
trainings and support to other teams.<br>
On my spare time I started learning Rust 3 years ago. I immediately fell in love with the language. I began implementing
some internal tools then started on a few open source projects.<br>
I am always keen on learning new things and I love sharing it with others."

#sidebar links
email: beltram.maldant(at)gmail.com
email-displayname: beltram.maldant
phone: xx.xx.xx.xx.xx
linkedin: beltram-maldant-2930b880
linkedin-displayname: Beltram Maldant
github: beltram
twitter: '@BeltramMaldant'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-112698702-1

# Build settings
encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development
